//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_product { get; set; }
        public string name { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> id_tag { get; set; }
        public Nullable<int> quantity_product { get; set; }
        public byte[] imageData { get; set; }
    
        public virtual Tags Tags { get; set; }
    }
}
